export const nigerianStates = [
  { option: "Abia", value: "abia" },
  { option: "Abuja", value: "abuja" },
  { option: "Adamawa", value: "adamawa" },
  { option: "Akwa Ibom", value: "akwa-ibom" },
  { option: "Anambra", value: "anambra" },
  { option: "Bauchi", value: "bauchi" },
  { option: "Bayelsa", value: "bayelsa" },
  { option: "Benue", value: "benue" },
  { option: "Borno", value: "borno" },
  { option: "Cross River", value: "cross-river" },
  { option: "Delta", value: "delta" },
  { option: "Ebonyi", value: "ebonyi" },
  { option: "Edo", value: "edo" },
  { option: "Ekiti", value: "ekiti" },
  { option: "Enugu", value: "enugu" },
  { option: "Gombe", value: "gombe" },
  { option: "Imo", value: "imo" },
  { option: "Jigawa", value: "jigawa" },
  { option: "Kaduna", value: "kaduna" },
  { option: "Kano", value: "kano" },
  { option: "Katsina", value: "katsina" },
  { option: "Kebbi", value: "kebbi" },
  { option: "Kogi", value: "kogi" },
  { option: "Kwara", value: "kwara" },
  { option: "Lagos", value: "lagos" },
  { option: "Nasarawa", value: "nasarawa" },
  { option: "Niger", value: "niger" },
  { option: "Ogun", value: "ogun" },
  { option: "Ondo", value: "ondo" },
  { option: "Osun", value: "osun" },
  { option: "Oyo", value: "oyo" },
  { option: "Plateau", value: "plateau" },
  { option: "Rivers", value: "rivers" },
  { option: "Sokoto", value: "sokoto" },
  { option: "Taraba", value: "taraba" },
  { option: "Yobe", value: "yobe" },
  { option: "Zamfara", value: "zamfara" },
];

export default nigerianStates;
